sigstore/terraform-modules

- gcp/modules/monitoring/prober/variables.tf
This fixes in an issue where `prober_data_absent_alert["http://timestamp-server.tsa-system.svc"]` currently gets enabled because timestamp is in the prober hosts list -- and we don't actually have timestamp running yet
I think it makes sense to to set the hosts variable in the environment configuration (based on what services the environment is running) in future, but for now avoid adding timestamp to services that will be probed by default.
> monitoring: Don't probe timestamp by default

- gcp/modules/sigstore/sigstore.tf
- gcp/modules/sigstore/variables.tf
- gcp/modules/timestamp/kms.tf
- gcp/modules/timestamp/variables.tf
Plan is to setup timestamp with a cert chain that contains a self signed root certificate and a signing certificate.
* Rename the ca key and variable so they do not claim to be "intermediate"
* rename the encryption key: there is nothing wrong with this name but the key exists on staging already in destroyed state. I'd like to avoid possible issue and use a new name (better ideas welcome too)
These changes may not be strictly speaking necessary (it's just name changes) but I figured it's useful to do now before we create the KMS resources for staging...
> timestamp: Rename key resource

- gcp/modules/sigstore/sigstore.tf
- gcp/modules/sigstore/variables.tf
Something is preventing overriding variable value for `monitoring.timestamp_enabled` later on: unlink it from `timestamp.enabled` variable and make sure the sigstore module defines a separate `monitoring.timestamp_enabled` variable
CC @bobcallaway this is per your suggestion
> sigstore: unlink timestamp and monitoring.timestamp

- gcp/modules/timestamp/service_accounts.tf
name in helm chart is `tsa-server` not `timestamp-server`
> update name of k8s service account per helm chart

- gcp/modules/monitoring/slo/main.tf
GCP now limits SLO windows to be `<= 24h`; this drops the config down to be API compliant; however we're not actually driving any notification on a slow-burn alert right now (which probably warrants further investigation).
this is preventing the rollout of the TSA SLOs.
> update slow burn window per API update

- gcp/modules/timestamp/service_accounts.tf
This was likely a leftover from when we had an asymmetric KMS key for signing timestamps. We only need the role to decrypt with a symmetric key, for Tink.
> Remove unneeded signerVerifier role from timestamp SA

- gcp/modules/tiles_tlog/spanner.tf
- gcp/modules/tiles_tlog/variables.tf
Make the Spanner instance and associated resources optional, as it isn't needed for a frozen log shard.
> Make Spanner instance optional for tiles_tlog

- gcp/modules/tiles_tlog/spanner.tf
- gcp/modules/tiles_tlog/variables.tf
deletion_protection is for databases only, not the instance.
> Remove deletion_protection for spanner instance

- gcp/modules/tiles_tlog/network.tf
gRPC healthchecks on GCP fail with connection issues regarding IPV6. I'm not sure what the root cause is, but I have found documentation that gRPC is primarily for Cloud Mesh Service and that gRPC healthchecks don't support TLS, which we have enabled for routing between the load balancer and backend service. The documentation suggests just using TCP, which only checks for a valid connection.
Also added healthcheck logging. NEGs are spun up so infrequently that the additional logging can be enabled unconditionally.
> Change gRPC healthcheck to test a TCP connection, add healthcheck logging

- gcp/modules/argocd/argocd.tf
- gcp/modules/argocd/variables.tf
https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.14-3.0/#removed-support-for-legacy-repo-config-in-argocd-cm
we need to specify things via a K8S secret for argocd v3+ isntead of within the argocd configMap
> support for argocd v3

- gcp/modules/monitoring/rekorv2/metrics.tf
- gcp/modules/monitoring/rekorv2/rekorv2_alerts.tf
- gcp/modules/monitoring/rekorv2/slo.tf
- gcp/modules/monitoring/rekorv2/variables.tf
- gcp/modules/monitoring/rekorv2/versions.tf
Copy the relevant alerts from Rekor v1 to a new Rekor v2 submodule in monitoring.
Like the main tiles_tlog module, this module may be re-used for individual shards, so it is not included in the monitoring module's sigstore.tf composition and instead must be individually called at the same level the tiles_tlog module is called.
The module is named rekorv2 instead of tiles_tlog because some of the metrics are specific to the rekor-tiles service and would not be relevant to a generic transparency log.  This is also why it must be called on its own and is not included as part of the tiles_tlog module.
There is no uptime check configured for the service itself because Rekor v2 has no native publicly exposed GET endpoint and it would not be an effective use of the log to POST entries to it …
> Add monitoring for Rekor v2

- gcp/modules/tiles_tlog/network.tf
- gcp/modules/tiles_tlog/variables.tf
This can be disabled via a variable, along with the healthcheck logging
> Configure logging for tlog backend service

- gcp/modules/monitoring/rekorv2/metrics.tf
- gcp/modules/monitoring/rekorv2/rekorv2_alerts.tf
Use the unique shard name for the metric, which will be specific to the shard and its namespace. Then the alert can uniquely refer to that metric and not generally to any shard.
> Fix name of rekorv2 metrics

- gcp/modules/tiles_tlog/network.tf
Connection draining[1] is recommended gives the external load balancer a grace period to drain connections from the application. The default timeout set by terraform is 300 seconds[2]. This is excessive considering the default termination grace period for a Kubernetes pod is 30 seconds, and a healthy Rekor request should last no more than 10 seconds. Set the timeout to 15 seconds to allow for a reasonably short termination period. The Kubernetes termination timeout will be updated as well.
[1] https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#500-series-errors
[2] https://github.com/hashicorp/terraform-provider-google/issues/13478
Partial https://github.com/sigstore/rekor-tiles/issues/370
> Set connection drain timeout for tiles_tlog

- gcp/modules/tiles_tlog/spanner.tf
Without this, turndown of the Spanner instance fails.
> Delete Spanner backups when deleting instance

- gcp/modules/tiles_tlog/gcs.tf
- gcp/modules/tiles_tlog/variables.tf
Read traffic will be served from GCS through a CDN. The CDN requires that the bucket be public. Currently, the bucket name is predictable so the CDN could be bypassed. This makes the bucket name unguessable. For backwards compatibility, the ID length is configurable since we have two buckets in staging without random IDs.
Ref https://github.com/sigstore/rekor-tiles/issues/355
> Append random ID to Tessera bucket name

- gcp/modules/monitoring/tuf/metrics.tf
The terraform apply for the new client metric failed.
Tweak the regexp escaping:
* escape `\` as `\\` -- this is for terraform: I originally thought terraform heredoc would not need this: it does
* Do not escape `/` -- GCP logging uses golang style regexp which does not require it: this also fixes an unrelated bug in the regex as "/s" now works as intended and not as literal "s"
There is no way to fully test this without TF apply but I have taken the expressions, unescaped them like I expect TF will, and fed them successfully to golang regexp tester.
> Fix regex in client metric

- gcp/modules/monitoring/infra/clients.json
- gcp/modules/monitoring/infra/dashboards.tf
* There is a significant amount of repetition in the dashboard definition (version charts are identical except for location and client name) but I feel it's still more maintainable this way than it would be if the client version chart json was generated with complex terraform code.
* This PR sort of depends on #90 (that adds the actual metric used here) -- I've kept this in a separate PR since that one already has a review.
* cosign data is missing in screenshot because cosign does not use tuf in staging. Adding other clients is easier once this exists in prod and we can see which clients should be added
> Add dashboard for client statistics

- gcp/modules/monitoring/rekorv2/active_shard/slo.tf
this was broken in #109, needs to refer to a dir two levels down now
> fix path in rekorv2 slo

- gcp/modules/monitoring/infra/dashboards.tf
- gcp/modules/monitoring/infra/rekor_v1.json
- gcp/modules/monitoring/rekor/metrics.tf
The production environment had additional dashboards that were missed when the Rekor v1 dashboards were codified. This change updates the the dashboard JSON so that they match.
Added:
- Rekor-Traffic metric, which was hand-crafted in the production environment and is used for showing traffic by user agent
- Rekor API Response Codes dashboard
- New Log Entries dashboard
- API traffic by endpoint dashboard
- SQL Connection vs Load dashboard
- Rekor traffic by user agent (currently named "logging/user/Rekor-Traffic (filtered) [MEAN]" in prod)
Removed:
- prometheus/rekor_latency_by_api/histogram was filtering on the UUID entry read API and did not seem too useful, and was not present for the prod environment
Equivalent dashboards:
- Mean of Rekor API Latency over 1 minute dashboard
Staging …
> Add prod dashboards for Rekor
