sigstore/terraform-modules

- gcp/modules/argocd/versions.tf
- gcp/modules/audit/versions.tf
- gcp/modules/bastion/versions.tf
- gcp/modules/ca/versions.tf
- gcp/modules/ctlog/versions.tf
- gcp/modules/dex/versions.tf
- gcp/modules/external_secrets/versions.tf
- gcp/modules/fulcio/versions.tf
- gcp/modules/gke_cluster/versions.tf
- gcp/modules/monitoring/dex/versions.tf
- gcp/modules/monitoring/fulcio/versions.tf
- gcp/modules/monitoring/infra/versions.tf
- gcp/modules/monitoring/prober/versions.tf
- gcp/modules/monitoring/rekor/versions.tf
- gcp/modules/monitoring/slo/versions.tf
- gcp/modules/monitoring/timestamp/versions.tf
- gcp/modules/monitoring/versions.tf
- gcp/modules/mysql-shard/versions.tf
- gcp/modules/mysql/versions.tf
- gcp/modules/network/versions.tf
- gcp/modules/oslogin/versions.tf
- gcp/modules/project_roles/versions.tf
- gcp/modules/redis/versions.tf
- gcp/modules/rekor/versions.tf
- gcp/modules/sigstore/versions.tf
- gcp/modules/timestamp/versions.tf
- gcp/modules/tuf/versions.tf
> bump terraform version to 1.11.2

- .github/workflows/terraform.yml
> bump setup-go

- gcp/modules/monitoring/timestamp/timestamp_alerts.tf
Fixes: #14 
@haydentherapper @jku fyi
> add signing cert expiration alert

- gcp/modules/monitoring/timestamp/slo.tf
- gcp/modules/monitoring/variables.tf
> fix wrong name of prometheus metric in timestamp monitoring alert

- gcp/modules/external_secrets/external_secrets.tf
This is not used anywhere so let's get rid of it.
> remove unused service account key

- gcp/modules/argocd/versions.tf
- gcp/modules/audit/versions.tf
- gcp/modules/bastion/versions.tf
- gcp/modules/ca/versions.tf
- gcp/modules/ctlog/versions.tf
- gcp/modules/dex/versions.tf
- gcp/modules/external_secrets/versions.tf
- gcp/modules/fulcio/versions.tf
- gcp/modules/gke_cluster/versions.tf
- gcp/modules/monitoring/dex/versions.tf
- gcp/modules/monitoring/fulcio/versions.tf
- gcp/modules/monitoring/infra/versions.tf
- gcp/modules/monitoring/prober/versions.tf
- gcp/modules/monitoring/rekor/versions.tf
- gcp/modules/monitoring/slo/versions.tf
- gcp/modules/monitoring/timestamp/versions.tf
- gcp/modules/monitoring/versions.tf
- gcp/modules/mysql-shard/versions.tf
- gcp/modules/mysql/versions.tf
- gcp/modules/network/versions.tf
- gcp/modules/oslogin/versions.tf
- gcp/modules/project_roles/versions.tf
- gcp/modules/redis/versions.tf
- gcp/modules/rekor/versions.tf
- gcp/modules/sigstore/versions.tf
- gcp/modules/timestamp/versions.tf
- gcp/modules/tuf/versions.tf
> upgrade terraform version to 1.11.4

- gcp/modules/tiles_tlog/gcs.tf
- gcp/modules/tiles_tlog/kms.tf
- gcp/modules/tiles_tlog/main.tf
- gcp/modules/tiles_tlog/network.tf
- gcp/modules/tiles_tlog/spanner.tf
- gcp/modules/tiles_tlog/variables.tf
- gcp/modules/tiles_tlog/versions.tf
Fixes https://github.com/sigstore/rekor-tiles/issues/41
> Add rekor-tiles module

- gcp/modules/tiles_tlog/spanner.tf
> Fix count attributes on spanner resources

- gcp/modules/tiles_tlog/network.tf
- gcp/modules/tiles_tlog/variables.tf
This change adds a load balancer with a CDN and SSL for tiles_tlog.
Since the load balancer must conditionally route to either the
Kubernetes service or a bucket, it can't be managed in Kubernetes by the
Ingress resource and instead must be managed explicitly in Terraform.
The Helm chart will use annotations on the Service to create Network
Endpoint Groups[1] to which the load balancer can route.
Since the NEGs are created by Kubernetes, they won't exist the first time these
Terraform modules are run for a given shard. The order of operations on
first deployment of any shard is:
1. Run Terraform with network_endpoint_group_zones in the tiles-tlog
module set to empty.
2. Update the ArgoCD configuration to deploy the new tlog shard.
3. Update the Terraform input to set …
> Add LB and URL map resources for tiles-tlog

- gcp/modules/tiles_tlog/versions.tf
Was missed by dependabot for some reason
> Bump terraform version of tiles_tlog

- gcp/modules/tiles_tlog/kms.tf
> Fix KMS key_ring reference

- gcp/modules/tiles_tlog/spanner.tf
Rekor-tiles takes the name of the main Spanner db and appends -antispam to it.
> Fix name of the antispam Spanner db

- gcp/modules/tiles_tlog/spanner.tf
- gcp/modules/tiles_tlog/variables.tf
> Add deletion_protection opt to spanner resources

- gcp/modules/tiles_tlog/gcs.tf
Following the documentation, https://cloud.google.com/cdn/docs/setting-up-cdn-with-bucket#terraform_3, updating this from a legacy viewer role to object viewer.
> Update role for backend bucket access

- gcp/modules/tiles_tlog/network.tf
- gcp/modules/tiles_tlog/variables.tf
> Parameterize enabling cdn for tiles_tlog

- gcp/modules/tiles_tlog/spanner.tf
The workload seems to need project-scoped permission to write to the timeseries database, which the spanner-instance-scoped IAM binding does not allow. Add a custom role with minimal monitoring permissions and add the workload account to it for the project.
> Add SpannerMonitoringTimeseries custom role

- gcp/modules/tiles_tlog/network.tf
Trim the root zone suffix from the hostname.
> Fix URL map host name

- gcp/modules/argocd/argocd.tf
- gcp/modules/external_secrets/external_secrets.tf
> migrate to v1 CRD for external-secrets

- gcp/modules/mysql-shard/mysql.tf
- gcp/modules/mysql-shard/variables.tf
- gcp/modules/mysql/mysql.tf
- gcp/modules/mysql/variables.tf
- gcp/modules/sigstore/sigstore.tf
- gcp/modules/sigstore/variables.tf
> set database flags on mysql instances

- gcp/modules/audit/audit.tf
- gcp/modules/audit/variables.tf
- gcp/modules/sigstore/sigstore.tf
- gcp/modules/sigstore/variables.tf
> make audit log types configurable

- gcp/modules/audit/versions.tf
- gcp/modules/bastion/versions.tf
- gcp/modules/ca/versions.tf
- gcp/modules/ctlog/versions.tf
- gcp/modules/dex/versions.tf
- gcp/modules/external_secrets/versions.tf
- gcp/modules/fulcio/versions.tf
- gcp/modules/gke_cluster/versions.tf
- gcp/modules/monitoring/dex/versions.tf
- gcp/modules/monitoring/fulcio/versions.tf
- gcp/modules/monitoring/infra/versions.tf
- gcp/modules/monitoring/prober/versions.tf
- gcp/modules/monitoring/rekor/versions.tf
- gcp/modules/monitoring/slo/versions.tf
- gcp/modules/monitoring/timestamp/versions.tf
- gcp/modules/monitoring/versions.tf
- gcp/modules/mysql-shard/versions.tf
- gcp/modules/mysql/versions.tf
- gcp/modules/network/versions.tf
- gcp/modules/oslogin/versions.tf
- gcp/modules/project_roles/versions.tf
- gcp/modules/redis/versions.tf
- gcp/modules/rekor/versions.tf
- gcp/modules/sigstore/versions.tf
- gcp/modules/tiles_tlog/versions.tf
- gcp/modules/timestamp/versions.tf
- gcp/modules/tuf/versions.tf
Reverts sigstore/terraform-modules#46
Needing to make some other changes first before handling updates
> Revert "Bump the terraform group across 27 directories with 1 update"

- gcp/modules/audit/versions.tf
- gcp/modules/bastion/versions.tf
- gcp/modules/ca/versions.tf
- gcp/modules/ctlog/versions.tf
- gcp/modules/dex/versions.tf
- gcp/modules/external_secrets/versions.tf
- gcp/modules/fulcio/versions.tf
- gcp/modules/gke_cluster/versions.tf
- gcp/modules/monitoring/dex/versions.tf
- gcp/modules/monitoring/fulcio/versions.tf
- gcp/modules/monitoring/infra/versions.tf
- gcp/modules/monitoring/prober/versions.tf
- gcp/modules/monitoring/rekor/versions.tf
- gcp/modules/monitoring/slo/versions.tf
- gcp/modules/monitoring/timestamp/versions.tf
- gcp/modules/monitoring/versions.tf
- gcp/modules/mysql-shard/versions.tf
- gcp/modules/mysql/versions.tf
- gcp/modules/network/versions.tf
- gcp/modules/oslogin/versions.tf
- gcp/modules/project_roles/versions.tf
- gcp/modules/redis/versions.tf
- gcp/modules/rekor/versions.tf
- gcp/modules/sigstore/versions.tf
- gcp/modules/tiles_tlog/versions.tf
- gcp/modules/timestamp/versions.tf
- gcp/modules/tuf/versions.tf
> bump terraform provider to 6.40.0

- gcp/modules/tiles_tlog/network.tf
Now that a number of resources have been made optional using the count meta-argument, these resources need to be accessed by index.
> Fix missing resource instance key

- gcp/modules/tiles_tlog/monitoring.tf
- gcp/modules/tiles_tlog/spanner.tf
- gcp/modules/tiles_tlog/variables.tf
Ensure this role isn't recreated by new instantiations of the module.
> Move custom role out of module

- gcp/modules/tiles_tlog/monitoring.tf
- gcp/modules/tiles_tlog/spanner.tf
> Fix reference to moved resource

- gcp/modules/monitoring/fulcio/fulcio_alerts.tf
- gcp/modules/monitoring/rekor/rekor_alerts.tf
- gcp/modules/monitoring/rekorv2/rekorv2_alerts.tf
- gcp/modules/monitoring/slo/main.tf
- gcp/modules/monitoring/timestamp/timestamp_alerts.tf
- gcp/modules/tiles_tlog/variables.tf
Also fixed some spelling and grammar errors.
> Add shard name for Rekor v2 alerts, dependency for SLO alerts

- gcp/modules/monitoring/infra/alerts.tf
- gcp/modules/monitoring/infra/dashboards.tf
Configure alerts for CPU and disk usage as recommended in the
documentation[1]. Add dashboards for CPU usage - there is already a
default dashboard for bytes used.
Partial https://github.com/sigstore/rekor-tiles/issues/410
> Add alerts and dashboards for Spanner

- gcp/modules/tiles_tlog/network.tf
Terraform does not update the load balancer before deleting the backend service objects, which causes a resource-in-use error. https://github.com/hashicorp/terraform-provider-google/issues/4543 notes this as a solution.
> Change lifecycle for url map

- gcp/modules/monitoring/rekorv2/lb/versions.tf
> Bump rekorv2 lb monitoring provider versions

- gcp/modules/monitoring/rekor/metrics.tf
> Fix rekor traffic metrics filter syntax
